"""followers

Revision ID: 615d6522ea18
Revises: 74defcf91031
Create Date: 2019-11-24 22:22:47.466220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615d6522ea18'
down_revision = '74defcf91031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
