"""added new fields to User model

Revision ID: 74defcf91031
Revises: e97e31f74f40
Create Date: 2019-11-21 22:29:00.524690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74defcf91031'
down_revision = 'e97e31f74f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
